language: node_js

node_js:
  - "11"

install:
  - npm install
  - rm -rf .git

script:
  - npm run build
  - echo 'Start updating example'
  - git clone https://${GH_REF} -b example tmpdir
  - cp -r tmpdir/.git dist
  - cp README.md dist/about.md
  - cd dist
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} example
  - echo 'Start updating build'
  - cd ..
  - rm -rf tmpdir dist/.git
  - git clone https://${GH_REF} -b ${P_BRANCH} tmpdir
  - cp -r tmpdir/.git dist
  - cd dist
  - rm -rf foo *.md
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} ${P_BRANCH}

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/MarkdownToHTML.git
    - P_BRANCH: build

addons:
  hosts:
    - ${WEBHOOK}
